//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeCharming.Common.Sending.BeCharming.Common.Service
{


  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "BeCharming.Common.Service.IListener")]
  public interface IListener
  {

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IListener/Echo", ReplyAction = "http://tempuri.org/IListener/EchoResponse")]
    string Echo(string message);
  }

  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  public interface IListenerChannel : BeCharming.Common.Service.IListener, System.ServiceModel.IClientChannel
  {
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  public partial class ListenerClient : System.ServiceModel.ClientBase<BeCharming.Common.Service.IListener>, BeCharming.Common.Service.IListener
  {

    public ListenerClient()
    {
    }

    public ListenerClient(string endpointConfigurationName) :
      base(endpointConfigurationName)
    {
    }

    public ListenerClient(string endpointConfigurationName, string remoteAddress) :
      base(endpointConfigurationName, remoteAddress)
    {
    }

    public ListenerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
      base(endpointConfigurationName, remoteAddress)
    {
    }

    public ListenerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
      base(binding, remoteAddress)
    {
    }

    public string Echo(string message)
    {
      return base.Channel.Echo(message);
    }
  }
}
